import '../domain/entities/activo_fijo.dart';
import '../domain/entities/alerta_seguridad.dart';
import '../domain/entities/cliente.dart';
import '../domain/entities/factura_cliente.dart';
import '../domain/entities/factura_proveedor.dart';
import '../domain/entities/item_inventario.dart';
import '../domain/entities/poliza_seguro.dart';
import '../domain/entities/unidad.dart';
import '../domain/entities/viaje.dart';

abstract final class DemoData {
  // ── Viajes ────────────────────────────────────────────────────────────────

  static final List<Viaje> viajes = [
    Viaje(
      id: 'v001',
      unidadId: 'u001',
      operadorId: 'op001',
      operadorNombre: 'Carlos Mendoza',
      origenDescripcion: 'CDMX — Bodega Central Vallejo',
      destinoDescripcion: 'Monterrey — Centro de Distribución',
      estado: EstadoViaje.enCurso,
      litrosCargados: 280,
      litrosConsumiidosTelemetria: 143,
      litrosConsumiidosTickets: 158,
      varianzaCombustible: 0.095,
      nivelAlerta: NivelAlertaViaje.bandajaRoja,
      tco: const TcoViaje(
        combustible:   14220,
        mantenimiento: 1800,
        peajes:        540,
        otros:         320,
      ),
      fechaInicio: DateTime(2026, 6, 5, 8, 30),
      createdAt:   DateTime(2026, 6, 5, 7, 45),
      updatedAt:   DateTime(2026, 6, 5, 11, 20),
    ),
    Viaje(
      id: 'v002',
      unidadId: 'u002',
      operadorId: 'op002',
      operadorNombre: 'Rodrigo Vargas',
      origenDescripcion: 'Guadalajara — Planta Los Altos',
      destinoDescripcion: 'CDMX — Bodega Sur Iztapalapa',
      estado: EstadoViaje.enCurso,
      litrosCargados: 220,
      litrosConsumiidosTelemetria: 86,
      litrosConsumiidosTickets: 87,
      varianzaCombustible: 0.012,
      nivelAlerta: NivelAlertaViaje.ninguna,
      tco: const TcoViaje(
        combustible:   9570,
        mantenimiento: 950,
        peajes:        480,
        otros:         150,
      ),
      fechaInicio: DateTime(2026, 6, 5, 6, 0),
      createdAt:   DateTime(2026, 6, 4, 23, 0),
      updatedAt:   DateTime(2026, 6, 5, 10, 45),
    ),
    Viaje(
      id: 'v003',
      unidadId: 'u003',
      operadorId: 'op003',
      operadorNombre: 'Ana Pérez',
      origenDescripcion: 'Querétaro — CEDIS Norte',
      destinoDescripcion: 'León — Almacén Industrial',
      estado: EstadoViaje.programado,
      litrosCargados: 0,
      litrosConsumiidosTelemetria: 0,
      litrosConsumiidosTickets: 0,
      nivelAlerta: NivelAlertaViaje.ninguna,
      tco: const TcoViaje(),
      createdAt: DateTime(2026, 6, 5, 9, 0),
      updatedAt: DateTime(2026, 6, 5, 9, 0),
    ),
    Viaje(
      id: 'v004',
      unidadId: 'u004',
      operadorId: 'op004',
      operadorNombre: 'Miguel Torres',
      origenDescripcion: 'Tijuana — Puerto de Entrada',
      destinoDescripcion: 'Hermosillo — Planta Norte',
      estado: EstadoViaje.enCurso,
      litrosCargados: 350,
      litrosConsumiidosTelemetria: 190,
      litrosConsumiidosTickets: 191,
      varianzaCombustible: 0.005,
      nivelAlerta: NivelAlertaViaje.ninguna,
      tco: const TcoViaje(
        combustible:   18900,
        mantenimiento: 2100,
        peajes:        920,
        otros:         430,
      ),
      fechaInicio: DateTime(2026, 6, 4, 22, 0),
      createdAt:   DateTime(2026, 6, 4, 20, 30),
      updatedAt:   DateTime(2026, 6, 5, 8, 15),
    ),
    // ── Viajes históricos completados (para historial + facturas) ─────────────
    Viaje(
      id: 'hist-v001',
      unidadId: 'u001',
      operadorId: 'op001',
      operadorNombre: 'Carlos Mendoza',
      origenDescripcion: 'CDMX — Bodega Central Vallejo',
      destinoDescripcion: 'Monterrey — Bodega Norte',
      estado: EstadoViaje.completado,
      litrosCargados: 265,
      litrosConsumiidosTelemetria: 148,
      litrosConsumiidosTickets: 157,
      varianzaCombustible: 0.057,
      nivelAlerta: NivelAlertaViaje.bandajaRoja,
      justificacionVarianza: 'Tráfico pesado en Saltillo — consumo adicional justificado.',
      tco: const TcoViaje(
        combustible:   13420,
        mantenimiento: 1650,
        peajes:        520,
        otros:         280,
      ),
      fechaInicio: DateTime(2026, 2, 10, 8, 0),
      fechaFin:    DateTime(2026, 2, 12, 18, 30),
      createdAt:   DateTime(2026, 2, 10, 7, 30),
      updatedAt:   DateTime(2026, 2, 12, 18, 30),
    ),
    Viaje(
      id: 'hist-v002',
      unidadId: 'u002',
      operadorId: 'op002',
      operadorNombre: 'Rodrigo Vargas',
      origenDescripcion: 'Guadalajara — Planta Los Altos',
      destinoDescripcion: 'CDMX — Centro Distribución',
      estado: EstadoViaje.completado,
      litrosCargados: 210,
      litrosConsumiidosTelemetria: 92,
      litrosConsumiidosTickets: 93,
      varianzaCombustible: 0.011,
      nivelAlerta: NivelAlertaViaje.ninguna,
      tco: const TcoViaje(
        combustible:   9200,
        mantenimiento: 980,
        peajes:        460,
        otros:         120,
      ),
      fechaInicio: DateTime(2026, 3, 1, 7, 0),
      fechaFin:    DateTime(2026, 3, 2, 20, 0),
      createdAt:   DateTime(2026, 2, 28, 22, 0),
      updatedAt:   DateTime(2026, 3, 2, 20, 0),
    ),
    Viaje(
      id: 'hist-v003',
      unidadId: 'u003',
      operadorId: 'op003',
      operadorNombre: 'Ana Pérez',
      origenDescripcion: 'Querétaro — CEDIS Norte',
      destinoDescripcion: 'León — Almacén Industrial',
      estado: EstadoViaje.completado,
      litrosCargados: 120,
      litrosConsumiidosTelemetria: 55,
      litrosConsumiidosTickets: 56,
      varianzaCombustible: 0.018,
      nivelAlerta: NivelAlertaViaje.ninguna,
      tco: const TcoViaje(
        combustible:   5400,
        mantenimiento: 600,
        peajes:        180,
        otros:         90,
      ),
      fechaInicio: DateTime(2026, 5, 25, 9, 0),
      fechaFin:    DateTime(2026, 5, 25, 16, 0),
      createdAt:   DateTime(2026, 5, 25, 8, 30),
      updatedAt:   DateTime(2026, 5, 25, 16, 0),
    ),
    Viaje(
      id: 'hist-v004',
      unidadId: 'u004',
      operadorId: 'op004',
      operadorNombre: 'Miguel Torres',
      origenDescripcion: 'Tijuana — Puerto de Entrada',
      destinoDescripcion: 'CEDIS Sur — Iztapalapa CDMX',
      estado: EstadoViaje.completado,
      litrosCargados: 340,
      litrosConsumiidosTelemetria: 185,
      litrosConsumiidosTickets: 186,
      varianzaCombustible: 0.005,
      nivelAlerta: NivelAlertaViaje.ninguna,
      tco: const TcoViaje(
        combustible:   18200,
        mantenimiento: 2050,
        peajes:        890,
        otros:         410,
      ),
      fechaInicio: DateTime(2026, 4, 12, 20, 0),
      fechaFin:    DateTime(2026, 4, 15, 10, 0),
      createdAt:   DateTime(2026, 4, 12, 18, 0),
      updatedAt:   DateTime(2026, 4, 15, 10, 0),
    ),
  ];

  // ── Unidades ─────────────────────────────────────────────────────────────

  static final List<Unidad> unidades = [
    Unidad(
      id: 'u001',
      placas: 'ABC-123-D',
      modelo: 'Kenworth T680',
      anio: 2021,
      estado: EstadoUnidad.activa,
      operadorAsignadoId: 'op001',
      ultimaPosicion:
          const GeoPoint(lat: 22.1565, lng: -100.9855), // SLP
      odometro: 148320,
      proximoMantenimientoOdometro: 150000,
      capacidadTanqueLitros: 800,
    ),
    Unidad(
      id: 'u002',
      placas: 'XYZ-456-E',
      modelo: 'Freightliner Cascadia',
      anio: 2022,
      estado: EstadoUnidad.activa,
      operadorAsignadoId: 'op002',
      ultimaPosicion:
          const GeoPoint(lat: 20.6597, lng: -103.3496), // GDL
      odometro: 89450,
      proximoMantenimientoOdometro: 90000,
      capacidadTanqueLitros: 750,
    ),
    Unidad(
      id: 'u003',
      placas: 'QRS-789-F',
      modelo: 'Volvo FH',
      anio: 2020,
      estado: EstadoUnidad.mantenimiento,
      operadorAsignadoId: 'op003',
      ultimaPosicion:
          const GeoPoint(lat: 20.5881, lng: -100.3899), // QRO
      odometro: 212100,
      proximoMantenimientoOdometro: 212500, // Requiere servicio! (< 500)
      capacidadTanqueLitros: 700,
    ),
    Unidad(
      id: 'u004',
      placas: 'TUV-012-G',
      modelo: 'Peterbilt 579',
      anio: 2023,
      estado: EstadoUnidad.activa,
      operadorAsignadoId: 'op004',
      ultimaPosicion:
          const GeoPoint(lat: 30.6995, lng: -112.0887), // Hermosillo
      odometro: 34780,
      proximoMantenimientoOdometro: 40000,
      capacidadTanqueLitros: 900,
    ),
  ];

  // ── Clientes ─────────────────────────────────────────────────────────────

  static final List<Cliente> clientes = [
    const Cliente(
      id: 'c001',
      nombre: 'Bodega Norte — Monterrey',
      direccion: 'Av. Constitución 145, Monterrey, N.L.',
      posicion: GeoPoint(lat: 25.6866, lng: -100.3161),
      telefono: '+52 81 8888 0001',
      contacto: 'Ing. Ramírez',
    ),
    const Cliente(
      id: 'c002',
      nombre: 'Centro Distribución GDL',
      direccion: 'Blvd. Adolfo López Mateos 340, Guadalajara, Jal.',
      posicion: GeoPoint(lat: 20.6597, lng: -103.3496),
      telefono: '+52 33 7777 0002',
      contacto: 'Lic. Flores',
    ),
    const Cliente(
      id: 'c003',
      nombre: 'Almacén Industrial León',
      direccion: 'Blvd. López Mateos Nte. 2208, León, Gto.',
      posicion: GeoPoint(lat: 21.1619, lng: -101.6824),
      telefono: '+52 47 7120 0003',
      contacto: 'Sr. Castro',
    ),
    const Cliente(
      id: 'c004',
      nombre: 'CEDIS Sur CDMX',
      direccion: 'Eje Central Lázaro Cárdenas 911, Iztapalapa, CDMX',
      posicion: GeoPoint(lat: 19.3643, lng: -99.0862),
      telefono: '+52 55 5555 0004',
      contacto: 'Dra. Mendoza',
    ),
    const Cliente(
      id: 'c005',
      nombre: 'Planta Bajío Querétaro',
      direccion: 'Av. 5 de Febrero 102, Querétaro, Qro.',
      posicion: GeoPoint(lat: 20.5888, lng: -100.3899),
      telefono: '+52 44 2200 0005',
      contacto: 'Ing. Ortega',
    ),
    const Cliente(
      id: 'c006',
      nombre: 'Puerto Seco San Luis',
      direccion: 'Carretera 57 Km. 3.5, San Luis Potosí, S.L.P.',
      posicion: GeoPoint(lat: 22.1566, lng: -100.9855),
      telefono: '+52 44 4812 0006',
      contacto: 'C.P. Gutiérrez',
    ),
    const Cliente(
      id: 'c007',
      nombre: 'Centro Logístico Hermosillo',
      direccion: 'Blvd. Solidaridad 203, Hermosillo, Son.',
      posicion: GeoPoint(lat: 29.0729, lng: -110.9559),
      telefono: '+52 66 2214 0007',
      contacto: 'Sr. Valenzuela',
    ),
    const Cliente(
      id: 'c008',
      nombre: 'Distribuidora Frontera',
      direccion: 'Av. Internacional 1401, Tijuana, B.C.',
      posicion: GeoPoint(lat: 32.5340, lng: -116.9320),
      telefono: '+52 66 4680 0008',
      contacto: 'Lic. Morales',
    ),
  ];

  // ── Activos Fijos ─────────────────────────────────────────────────────────
  // Vida útil 10 años, valor residual 10% del costo. Referencia: precios MXN 2021-2023.

  static final List<ActivoFijo> activosFijos = [
    ActivoFijo(
      id: 'af001',
      unidadId: 'u001',
      descripcion: 'Kenworth T680 2021 — ABC-123-D',
      fechaAdquisicion: DateTime(2021, 1, 15),
      costoAdquisicion: 3100000,
      valorResidual: 310000,
      vidaUtilAnios: 10,
    ),
    ActivoFijo(
      id: 'af002',
      unidadId: 'u002',
      descripcion: 'Freightliner Cascadia 2022 — XYZ-456-E',
      fechaAdquisicion: DateTime(2022, 3, 10),
      costoAdquisicion: 2950000,
      valorResidual: 295000,
      vidaUtilAnios: 10,
    ),
    ActivoFijo(
      id: 'af003',
      unidadId: 'u003',
      descripcion: 'Volvo FH 2020 — QRS-789-F',
      fechaAdquisicion: DateTime(2020, 6, 1),
      costoAdquisicion: 2750000,
      valorResidual: 275000,
      vidaUtilAnios: 10,
    ),
    ActivoFijo(
      id: 'af004',
      unidadId: 'u004',
      descripcion: 'Peterbilt 579 2023 — TUV-012-G',
      fechaAdquisicion: DateTime(2023, 8, 20),
      costoAdquisicion: 3400000,
      valorResidual: 340000,
      vidaUtilAnios: 10,
    ),
  ];

  // ── Pólizas de Seguro ─────────────────────────────────────────────────────
  // Fecha actual 2026-06-09: p002 próxima a vencer (21 días), p003 vencida (39 días).

  static final List<PolizaSeguro> polizas = [
    PolizaSeguro(
      id: 'ps001',
      tipo: TipoPoliza.responsabilidadCivil,
      aseguradora: 'AXA Seguros',
      numeroPoliza: 'POL-AXA-RC-2026-001',
      vigenciaInicio: DateTime(2026, 1, 1),
      vigenciaFin: DateTime(2027, 1, 1),
      primaMensual: 9200,
      modoPago: ModoPagoSeguro.mensual,
      coberturaMaxima: 5000000,
      deducible: 50000,
    ),
    PolizaSeguro(
      id: 'ps002',
      unidadId: 'u001',
      unidadPlacas: 'ABC-123-D',
      tipo: TipoPoliza.cargoTransportado,
      aseguradora: 'Mapfre México',
      numeroPoliza: 'POL-MAPFRE-CT-2026-014',
      vigenciaInicio: DateTime(2026, 3, 1),
      vigenciaFin: DateTime(2026, 6, 30),
      primaMensual: 3100,
      modoPago: ModoPagoSeguro.semestral,
      coberturaMaxima: 2000000,
      deducible: 20000,
    ),
    PolizaSeguro(
      id: 'ps003',
      unidadId: 'u003',
      unidadPlacas: 'QRS-789-F',
      tipo: TipoPoliza.todoRiesgo,
      aseguradora: 'GNP Seguros',
      numeroPoliza: 'POL-GNP-TR-2025-088',
      vigenciaInicio: DateTime(2025, 12, 1),
      vigenciaFin: DateTime(2026, 5, 1),
      primaMensual: 4500,
      modoPago: ModoPagoSeguro.semestral,
      coberturaMaxima: 3500000,
      deducible: 35000,
    ),
    PolizaSeguro(
      id: 'ps004',
      unidadId: 'u004',
      unidadPlacas: 'TUV-012-G',
      tipo: TipoPoliza.danosTerceros,
      aseguradora: 'HDI Seguros',
      numeroPoliza: 'POL-HDI-DT-2026-202',
      vigenciaInicio: DateTime(2026, 5, 1),
      vigenciaFin: DateTime(2027, 5, 1),
      primaMensual: 2800,
      modoPago: ModoPagoSeguro.anual,
      coberturaMaxima: 1500000,
      deducible: 15000,
    ),
  ];

  // ── Facturas de Clientes ──────────────────────────────────────────────────
  // Fecha actual 2026-06-09. fc001/fc002 cobradas, fc003 corriente, fc004 vencida 25d,
  // fc005 vencida 51d, fc006 vencida 98d.

  static final List<FacturaCliente> facturas = [
    FacturaCliente(
      id: 'fc001',
      viajeId: 'hist-v001',
      clienteId: 'c001',
      clienteNombre: 'Bodega Norte — Monterrey',
      numeroFactura: 'GL-2026-0001',
      fechaEmision: DateTime(2026, 2, 15),
      fechaVencimiento: DateTime(2026, 3, 17),
      monto: 21500,
      montoCobrado: 21500,
      estatus: EstatusFactura.cobrada,
      fechaCobro: DateTime(2026, 3, 10),
    ),
    FacturaCliente(
      id: 'fc002',
      viajeId: 'hist-v002',
      clienteId: 'c002',
      clienteNombre: 'Centro Distribución GDL',
      numeroFactura: 'GL-2026-0002',
      fechaEmision: DateTime(2026, 3, 1),
      fechaVencimiento: DateTime(2026, 3, 31),
      monto: 15200,
      montoCobrado: 15200,
      estatus: EstatusFactura.cobrada,
      fechaCobro: DateTime(2026, 3, 28),
    ),
    FacturaCliente(
      id: 'fc003',
      viajeId: 'hist-v003',
      clienteId: 'c003',
      clienteNombre: 'Almacén Industrial León',
      numeroFactura: 'GL-2026-0003',
      fechaEmision: DateTime(2026, 5, 25),
      fechaVencimiento: DateTime(2026, 6, 24),
      monto: 8900,
      estatus: EstatusFactura.pendiente,
    ),
    FacturaCliente(
      id: 'fc004',
      viajeId: 'hist-v004',
      clienteId: 'c004',
      clienteNombre: 'CEDIS Sur CDMX',
      numeroFactura: 'GL-2026-0004',
      fechaEmision: DateTime(2026, 4, 15),
      fechaVencimiento: DateTime(2026, 5, 15),
      monto: 27800,
      estatus: EstatusFactura.vencida,
    ),
    FacturaCliente(
      id: 'fc005',
      viajeId: 'hist-v001',
      clienteId: 'c005',
      clienteNombre: 'Planta Bajío Querétaro',
      numeroFactura: 'GL-2026-0005',
      fechaEmision: DateTime(2026, 3, 20),
      fechaVencimiento: DateTime(2026, 4, 19),
      monto: 12400,
      estatus: EstatusFactura.vencida,
    ),
    FacturaCliente(
      id: 'fc006',
      viajeId: 'hist-v002',
      clienteId: 'c006',
      clienteNombre: 'Puerto Seco San Luis',
      numeroFactura: 'GL-2026-0006',
      fechaEmision: DateTime(2026, 2, 1),
      fechaVencimiento: DateTime(2026, 3, 3),
      monto: 19600,
      estatus: EstatusFactura.vencida,
    ),
    // ── Cobros históricos para graficar el resumen mensual ─────────────────
    FacturaCliente(
      id: 'fc007',
      viajeId: 'hist-v001',
      clienteId: 'c007',
      clienteNombre: 'Centro Logístico Hermosillo',
      numeroFactura: 'GL-2026-0007',
      fechaEmision: DateTime(2026, 1, 20),
      fechaVencimiento: DateTime(2026, 2, 20),
      monto: 17400,
      montoCobrado: 17400,
      estatus: EstatusFactura.cobrada,
      fechaCobro: DateTime(2026, 2, 18),
    ),
    FacturaCliente(
      id: 'fc008',
      viajeId: 'hist-v003',
      clienteId: 'c003',
      clienteNombre: 'Almacén Industrial León',
      numeroFactura: 'GL-2026-0008',
      fechaEmision: DateTime(2026, 4, 5),
      fechaVencimiento: DateTime(2026, 5, 5),
      monto: 9600,
      montoCobrado: 9600,
      estatus: EstatusFactura.cobrada,
      fechaCobro: DateTime(2026, 4, 28),
    ),
    FacturaCliente(
      id: 'fc009',
      viajeId: 'hist-v004',
      clienteId: 'c004',
      clienteNombre: 'CEDIS Sur CDMX',
      numeroFactura: 'GL-2026-0009',
      fechaEmision: DateTime(2026, 5, 1),
      fechaVencimiento: DateTime(2026, 5, 31),
      monto: 23100,
      montoCobrado: 23100,
      estatus: EstatusFactura.cobrada,
      fechaCobro: DateTime(2026, 5, 22),
    ),
  ];

  // ── Facturas de Proveedores ───────────────────────────────────────────────
  // Fecha actual 2026-06-09. fp001 corriente (+16d), fp002 vencida 20d,
  // fp003 vencida 45d, fp004 pagada (mar-26), fp005 vencida 8d, fp006 vencida 99d.

  static final List<FacturaProveedor> facturasProveedor = [
    FacturaProveedor(
      id: 'fp001',
      proveedorId: 'prov-pemex',
      proveedorNombre: 'Pemex Magisterio',
      tipoProveedor: TipoProveedor.combustible,
      numeroFactura: 'PMX-2026-0312',
      fechaEmision: DateTime(2026, 5, 15),
      fechaVencimiento: DateTime(2026, 6, 25),
      monto: 28500,
      estatus: EstatusFacturaProveedor.pendiente,
    ),
    FacturaProveedor(
      id: 'fp002',
      proveedorId: 'prov-bridge',
      proveedorNombre: 'Bridgestone México',
      tipoProveedor: TipoProveedor.llantas,
      numeroFactura: 'BRI-2026-0088',
      fechaEmision: DateTime(2026, 4, 1),
      fechaVencimiento: DateTime(2026, 5, 20),
      monto: 42000,
      estatus: EstatusFacturaProveedor.vencida,
    ),
    FacturaProveedor(
      id: 'fp003',
      proveedorId: 'prov-taller',
      proveedorNombre: 'Taller TorqueMaster',
      tipoProveedor: TipoProveedor.mantenimiento,
      numeroFactura: 'TQM-2026-0055',
      fechaEmision: DateTime(2026, 3, 20),
      fechaVencimiento: DateTime(2026, 4, 25),
      monto: 15800,
      estatus: EstatusFacturaProveedor.vencida,
    ),
    FacturaProveedor(
      id: 'fp004',
      proveedorId: 'prov-pemex',
      proveedorNombre: 'Pemex Magisterio',
      tipoProveedor: TipoProveedor.combustible,
      numeroFactura: 'PMX-2026-0211',
      fechaEmision: DateTime(2026, 3, 1),
      fechaVencimiento: DateTime(2026, 3, 31),
      monto: 31200,
      montoPagado: 31200,
      estatus: EstatusFacturaProveedor.pagada,
      fechaPago: DateTime(2026, 3, 28),
    ),
    FacturaProveedor(
      id: 'fp005',
      proveedorId: 'prov-gnp',
      proveedorNombre: 'GNP Seguros',
      tipoProveedor: TipoProveedor.seguro,
      numeroFactura: 'GNP-2026-1044',
      fechaEmision: DateTime(2026, 5, 1),
      fechaVencimiento: DateTime(2026, 6, 1),
      monto: 9200,
      estatus: EstatusFacturaProveedor.vencida,
    ),
    FacturaProveedor(
      id: 'fp006',
      proveedorId: 'prov-refmx',
      proveedorNombre: 'Refacciones MX',
      tipoProveedor: TipoProveedor.refacciones,
      numeroFactura: 'RMX-2026-0034',
      fechaEmision: DateTime(2026, 2, 10),
      fechaVencimiento: DateTime(2026, 3, 2),
      monto: 8400,
      estatus: EstatusFacturaProveedor.vencida,
    ),
    // ── Pagos históricos para graficar el resumen mensual ──────────────────
    FacturaProveedor(
      id: 'fp007',
      proveedorId: 'prov-pemex',
      proveedorNombre: 'Pemex Magisterio',
      tipoProveedor: TipoProveedor.combustible,
      numeroFactura: 'PMX-2026-0118',
      fechaEmision: DateTime(2026, 1, 15),
      fechaVencimiento: DateTime(2026, 2, 15),
      monto: 24600,
      montoPagado: 24600,
      estatus: EstatusFacturaProveedor.pagada,
      fechaPago: DateTime(2026, 2, 12),
    ),
    FacturaProveedor(
      id: 'fp008',
      proveedorId: 'prov-taller',
      proveedorNombre: 'Taller TorqueMaster',
      tipoProveedor: TipoProveedor.mantenimiento,
      numeroFactura: 'TQM-2026-0041',
      fechaEmision: DateTime(2026, 3, 28),
      fechaVencimiento: DateTime(2026, 4, 28),
      monto: 11200,
      montoPagado: 11200,
      estatus: EstatusFacturaProveedor.pagada,
      fechaPago: DateTime(2026, 4, 25),
    ),
    FacturaProveedor(
      id: 'fp009',
      proveedorId: 'prov-pemex',
      proveedorNombre: 'Pemex Magisterio',
      tipoProveedor: TipoProveedor.combustible,
      numeroFactura: 'PMX-2026-0278',
      fechaEmision: DateTime(2026, 5, 1),
      fechaVencimiento: DateTime(2026, 5, 31),
      monto: 27800,
      montoPagado: 27800,
      estatus: EstatusFacturaProveedor.pagada,
      fechaPago: DateTime(2026, 5, 28),
    ),
  ];

  // ── Inventario ────────────────────────────────────────────────────────────
  // 3 ítems bajo mínimo: inv002 (llantas), inv004 (aceite TX), inv006 (filtros combustible).

  static final List<ItemInventario> itemsInventario = [
    ItemInventario(
      id: 'inv001',
      nombre: 'Llantas 11R22.5 Michelin',
      categoria: CategoriaInventario.llantas,
      unidadMedida: UnidadMedida.piezas,
      stockActual: 8,
      stockMinimo: 4,
      precioUnitario: 3500,
      ultimaActualizacion: DateTime(2026, 6, 1),
    ),
    ItemInventario(
      id: 'inv002',
      nombre: 'Llantas 295/80R22.5 Bridgestone',
      categoria: CategoriaInventario.llantas,
      unidadMedida: UnidadMedida.piezas,
      stockActual: 2,
      stockMinimo: 4,
      precioUnitario: 3800,
      ultimaActualizacion: DateTime(2026, 6, 5),
    ),
    ItemInventario(
      id: 'inv003',
      nombre: 'Aceite Motor Shell Rimula 15W40',
      categoria: CategoriaInventario.aceites,
      unidadMedida: UnidadMedida.litros,
      stockActual: 120,
      stockMinimo: 50,
      precioUnitario: 85,
      ultimaActualizacion: DateTime(2026, 5, 28),
    ),
    ItemInventario(
      id: 'inv004',
      nombre: 'Aceite Transmisión Mobil Delvac',
      categoria: CategoriaInventario.aceites,
      unidadMedida: UnidadMedida.litros,
      stockActual: 15,
      stockMinimo: 30,
      precioUnitario: 95,
      ultimaActualizacion: DateTime(2026, 6, 3),
    ),
    ItemInventario(
      id: 'inv005',
      nombre: 'Filtros de Aceite Fleetguard',
      categoria: CategoriaInventario.refacciones,
      unidadMedida: UnidadMedida.piezas,
      stockActual: 20,
      stockMinimo: 8,
      precioUnitario: 180,
      ultimaActualizacion: DateTime(2026, 5, 20),
    ),
    ItemInventario(
      id: 'inv006',
      nombre: 'Filtros de Combustible Baldwin',
      categoria: CategoriaInventario.refacciones,
      unidadMedida: UnidadMedida.piezas,
      stockActual: 3,
      stockMinimo: 6,
      precioUnitario: 220,
      ultimaActualizacion: DateTime(2026, 6, 7),
    ),
    ItemInventario(
      id: 'inv007',
      nombre: 'Zapatas de Freno Brembo',
      categoria: CategoriaInventario.refacciones,
      unidadMedida: UnidadMedida.piezas,
      stockActual: 12,
      stockMinimo: 4,
      precioUnitario: 850,
      ultimaActualizacion: DateTime(2026, 5, 15),
    ),
    ItemInventario(
      id: 'inv008',
      nombre: 'Anticongelante Havoline 50/50',
      categoria: CategoriaInventario.aceites,
      unidadMedida: UnidadMedida.litros,
      stockActual: 25,
      stockMinimo: 20,
      precioUnitario: 45,
      ultimaActualizacion: DateTime(2026, 6, 2),
    ),
  ];

  // ── Alertas ───────────────────────────────────────────────────────────────

  static final List<AlertaSeguridad> alertas = [
    AlertaSeguridad(
      id: 'a001',
      viajeId: 'v001',
      operadorId: 'op001',
      unidadId: 'u001',
      tipo: TipoAlerta.sos,
      timestamp: DateTime(2026, 6, 5, 10, 15),
      posicion: const GeoPoint(lat: 22.1565, lng: -100.9855),
      estado: EstadoAlerta.activa,
    ),
    AlertaSeguridad(
      id: 'a002',
      viajeId: 'v001',
      operadorId: 'op001',
      unidadId: 'u001',
      tipo: TipoAlerta.varianzaCombustible,
      timestamp: DateTime(2026, 6, 5, 11, 30),
      posicion: const GeoPoint(lat: 22.1565, lng: -100.9855),
      estado: EstadoAlerta.activa,
    ),
  ];
}
