// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS no está configurado. Agrega GoogleService-Info.plist '
          'y ejecuta flutterfire configure --platforms=ios.',
        );
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no están configuradas para esta plataforma.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyMfRBqAsxJCXhvzsX3bz4ured5PHvSLc',
    appId: '1:78981510555:web:53945f5a95fc6729c31d3e',
    messagingSenderId: '78981510555',
    projectId: 'globo-logisti',
    authDomain: 'globo-logisti.firebaseapp.com',
    storageBucket: 'globo-logisti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA6WlyH70kVEfcgnho-Kb85dT4F34j56U',
    appId: '1:78981510555:android:11f6e3709d338bb7c31d3e',
    messagingSenderId: '78981510555',
    projectId: 'globo-logisti',
    storageBucket: 'globo-logisti.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyMfRBqAsxJCXhvzsX3bz4ured5PHvSLc',
    appId: '1:78981510555:web:4c67f4764858c23cc31d3e',
    messagingSenderId: '78981510555',
    projectId: 'globo-logisti',
    authDomain: 'globo-logisti.firebaseapp.com',
    storageBucket: 'globo-logisti.firebasestorage.app',
  );
}
